### ISSUE TITLE
Some functions are not being imported

### ISSUE THREAD

**Issue by Grench6** [nim-lang/bigints#117]
The compiler doesn't seem to be able to find some functions such as `invmod`, `toInt` or `powmod`.

An example from the [documentation](https://nimdocs.com/nim-lang/bigints/bigints.html#invmod%2CBigInt%2CBigInt):
```nim
import pkg/"bigints"
assert invmod(3.initBigInt, 7.initBigInt) == 5.initBigInt
```
Throws an error when compiling...
```
Error: undeclared identifier: 'invmod'
```
Everything looks fine in the [source ](https://github.com/nim-lang/bigints/blob/master/src/bigints.nim#L1176), does anybody knows what is going on?

**Comment by dlesnoff** [comment]
What is your version of bigints ?
You want to install devel version which contains a lot of bugfixes and addition to the API (and is quite stable, CI is rarely failing).
```nim
nimble install bigints@#head
```
By default, it installs the 0.5 version that is about 1.5 years old.

**Comment by Grench6** [comment]
Thanks, that was indeed the problem.

Someone should definitively consider changing that [nimdocs ](https://github.com/treeform/nimdocs)behavior.

But still, the inconsistency between the version inside the nimble file and the git tag should be fixed so everyone is able to download a more recent version by default.
