### ISSUE TITLE
bump new version

### ISSUE THREAD

**Issue by bung87** [nim-lang/bigints#122]

**Comment by dlesnoff** [comment]
Fixed by #126

**Comment by bung87** [comment]
still 1.0.0 last commit is last year.

**Comment by dlesnoff** [comment]
Oh you meant the library version. Sorry, I thought you meant the CI version. That's up to @narimiran

**Comment by narimiran** [comment]
Should we (just) bump the version number in `bigints.nimble`, or is a git tag / Github release necessary?

**Comment by bung87** [comment]
should done in both side as nimble use git tag

**Comment by narimiran** [comment]
Ok, both now done. We're at v1.1.0!
