### ISSUE TITLE
nimdocs.com going away

### ISSUE THREAD

**Issue by guzba** [nim-lang/bigints#125]
Hello, I wanted to give this repo a quick heads-up that nimdocs.com, which @treeform and I have been running, is going away in favor of using Github Actions + Github Pages.

nimdocs.com is currently linked to from this repo's readme for documentation.

My suggestion:

Add this Github Actions workflow file: https://github.com/treeform/nimtemplate/blob/master/.github/workflows/docs.yml (no need to change anything) to automatically generate docs in a branch called gh-pages. This branch will have the Docs content updated each push.

In the repo settings Page tab, you can then select that branch to serve (once the job has run once).

After that, https://nim-lang.github.io/bigints/ should be serving the most recently generated docs.

This is simpler than us running a server and all of that stuff and just as easy for repo maintainers so I think it is a better model.

I'll keep the server up for a bit yet but it is going away.

**Comment by dlesnoff** [comment]
@guzba Thanks for the notification, I am going to make a PR tonight.

**Comment by dlesnoff** [comment]
@narimiran Can you activate the GitHub pages in the repo?
My PR broke the YAML file.

**Comment by narimiran** [comment]
It should be activated now. Please let me know if it doesn't work.

**Comment by konsumlamm** [comment]
@narimiran did you select the `gh-pages` branch for deployment (Settings -> Pages -> Branch)?

**Comment by narimiran** [comment]
> @narimiran did you select the gh-pages branch for deployment (Settings -> Pages -> Branch)?

Now I did :)

**Comment by konsumlamm** [comment]
Nice, now it works.

**Comment by dlesnoff** [comment]
Thanks for fixing that!
