### ISSUE TITLE
[Feature request] `powmod`

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/bigints#45]
### Description

Provide a `powmod(base, exponent, modulus)` function that computes `(base ^ exponent) % modulus`, but more efficiently than the naive computation. In particular, it should avoid building up `BigInt`s that are substantially larger than `modulus`.

### Related work

* [D](https://dlang.org/phobos/std_bigint.html#.powmod)
* [Rust](https://docs.rs/num-bigint/0.4.3/num_bigint/struct.BigInt.html#method.modpow)

**Comment by dlesnoff** [comment]
We should first implement a gcd function and a bitops operation to count the number of bits.
I tried to implement it for prime modulus and to add some tests. I have to add sign handling too. I am unsure how to handle composite numbers. 
From a mathematical point of view, I would reduce the exponent modulo the euler totient function of the modulus, and compute the power modulo each factor. We compute the result back with CRT (Chinese Remainder Theorem).
But computing the euler totient is as hard as factoring the integer (for very large modulus). So there are probably more practical way. Maybe we should give the euler totient as an optional parameter ? It would avoid check if the modulus is prime and to factor it.
I checked Rust library but don't understand their logic. For BigInt, they call a function of another module named power (so I guess they do it the naive way ?). For BigUint, they use a "Montgomerry Ladder" for odd integers implemented in another file I could not find, and for even integers  I have not check it yet, but is handmade and optimized.

**Comment by konsumlamm** [comment]
For now, we could just implement it like `pow` (using binary exponentiation, but take the modulo every iteration, like the [D implementation](https://github.com/dlang/phobos/blob/4687883231eba3bda7691321f2af107fdb3d0a44/std/bigint.d#L2328) does) and optimize it later.
