### ISSUE TITLE
Support more characters for initializing a `BigInt` from a string

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/bigints#52]
Analogous to `-` for negative numbers, we could also support a leading `+`, which would be ignored. Another thing that would be nice is supporting `_` (which also get ignored), akin to normal int literals:
```nim
let a = initBigInt("+10_000_000_000")
```

**Comment by dlesnoff** [comment]
We could also change the toString function. I would add optional parameters to toString to add `_` and sign to the normal representation. By default the default parameters would not output them, so we can always get the number of digits in the specified radix representation.
