### ISSUE TITLE
Type conversion for small BigInts into integers

### ISSUE THREAD

**Issue by dlesnoff** [nim-lang/bigints#72]
Since BigInt's limb parameter has become private, thus we can not easily cast BigInts with absolute value less than `2^32` to an `int` or even a `uint32`. 
The only workaround yet is to use the keyword `cast[int]`. But this does not always do what we want.
To get only the smallest limb, we also have to define a mask like `2^32 - 1` and to apply an ineffective `and`.
Can we implement some functions like … ?:
- `toUint32(a: BigInt): uint32` returns the only limb for BigInts between 1-2^32 and +2^32-1 (small BigInts).
-  `toInt(a: BigInt): int` cast the BigInt if it is small enough, into an int, according to the sign of BigInt, with correct representation (2's complement) and raises a ValueError if the cast can not be done (if int is stored on 32 bits, it may not fit if the heavy weight bit of the uint32 corresponding to first limb is 1).
- `toUint64(a: BigInt): uint64` returns the uint64 made up of one to two limbs, if the BigInt is small enough.
-  `toFloat` like described in the similar issue #34.

**Comment by konsumlamm** [comment]
> The only workaround yet is to use the keyword `cast[int]`. But this does not always do what we want.

That never does what you want. I suggest you read the [documentation for `cast`](https://nim-lang.org/docs/manual.html#statements-and-expressions-type-casts), it merely reinterprets the underlying bits.

I generally agree that functions to convert a `BigInt` to some integer types are useful, but how should we handle the case of the `BigInt` being out of range? I see several possibilities:
* raise an exception
* return an [`Option`](https://nim-lang.org/docs/options.html#Option)
* return the lowest/highest value

**Comment by narimiran** [comment]
@Araq: you might be interested in this discussion, i.e. give your opinion on how to best proceed with this.

**Comment by dlesnoff** [comment]
We can not return the lowest/highest value for type conversions to integers as a BigInt can be any value that an int can contain.
The first solution forces the user to wrap any potentially dangerous cast in a `try .. except .. finally` clause.
I have not used `Option` in my programs yet, if I understand the user will have to check (everytime ?) whether the Option contains a value ?

**Comment by konsumlamm** [comment]
This issue should be reopened, `toSignedInt` only provides conversion to signed integers. I'd also argue that it should be renamed to `toInt` and also support unsigned integers (rather than adding a new `toUnsignedInt` function).

**Comment by Araq** [comment]
I also really need `pred`  and `succ`. Implementation can be as simple as:

```nim

proc pred*(a: BigInt; def = 1): BigInt =
  a - initBigInt(def)

proc succ*(a: BigInt; def = 1): BigInt =
  a + initBigInt(def)

```

**Comment by dlesnoff** [comment]
Should we not rather call them `inc` and `dec` like for `int` ?

**Comment by konsumlamm** [comment]
This has been addressed in https://github.com/nim-lang/bigints/pull/100.
