### ISSUE TITLE
Bitwise `not`

### ISSUE THREAD

**Issue by dlesnoff** [nim-lang/bigints#77]
In the README, there is a mention about a bitwise `not` operator. I would like to understand the use case of such an operator.
Is it not sufficient to just invert the bits of each limb ?
Should it modify the sign of the BigInt ? The previously implemented operators raises an exception if at least one of the inputs is negative.

Here is how I would code the operator `not`:
```nim
func `not`*(a : BigInt): BigInt =
  ## Bitwise `not` for `BigInt`s.
  runnableExamples:
  let
    a = 7.initBigInt
    assert not a == 8.initBigInt
  assert (not a.isNegative)
  result.limbs.setLen(a.limbs.len)
  for i in 0 ..< a.limbs.len:
    result.limbs[i] = not result.limbs[i]
```

**Comment by konsumlamm** [comment]
See also #51.

Your implementation wouldn't make sense, due to the way the `BigInt`s are stored. For example, `not 0'bi` should be `-1'bi` and not `0xFFFFFFFF'bi`, i.e. it should act as if the number was stored in 2's complement representation (which is what everyone uses for integers).

**Comment by dlesnoff** [comment]
This is indeed a duplicate of #51.
```nim
func `not`*(a: BigInt): BigInt = -a - 1
```
would be the simplest.
I think we could also use a cast to `int32` on highest limb : 
```nim
let leadingLimb = a.limbs[a.limbs.high]
let castLeadingLimb = cast[int32](not leadingLimb)
result.limbs[a.limbs.len-1] = abs(castLeadingLimb).uint32
```
 and set the sign as : 
 ```nim
 result.isNegative = a.isNegative xor (castLeadingLimb > 0)
 ```
