### ISSUE TITLE
Base multiplication returns wrong results for some big numbers

### ISSUE THREAD

**Issue by dlesnoff** [nim-lang/bigints#96]
```nim
when isMainModule:
  a = "1780983279228119273110576463639172624".initBigInt
  b = "1843917749452418885995463656480858321".initBigInt
  echo a.limbs.len
  echo b.limbs.len
  echo a*b
```
outputs :
```
4
4
3283986680046702618742503890385314117448805445290098330749803441805804304
```
It should output : 
```
4
4
3171901440890145063107180402349133639481893332927709969425239467271045376
```
Result obtained with SageMath, with Pari/GP and Wolfram/Alpha.
There are no tests for multiplication with more than two or three limbs.

**Comment by konsumlamm** [comment]
I can't reproduce this (your example is missing the `let`s, btw), I checked with WolframAlpha and it gives me 3283986680046702618742503890385314117448805445290098330749803441805804304, which is the current result.

**Comment by narimiran** [comment]
The calculator on my computer also produces `3283986680046702618742503890385314117448805445290098330749803441805804304`

**Comment by Araq** [comment]
No worries.

**Comment by konsumlamm** [comment]
We should add a test case for this anyway, it doesn't hurt to test multiplication for big `BigInt`s.
